### ISSUE TITLE
v3(lib): routing examples rework — prerender, static adapter, error pages

### ISSUE THREAD

**Issue by jarda-svoboda** [sveltekit-i18n/lib#230]
Part of the v3 release train (#214). Companion to the docs/examples bullet of #229, split out because routing examples are the **single most recurring pain in this tracker**.

**Sequenced after #253.** The documentation site is built first and is the first real consumer of the static routing recipe, so this issue **extracts and generalizes what the site already does** into standalone examples, rather than inventing them and having the site copy them. The recipe itself is verified — the measurements are in the [#149 comment](https://github.com/sveltekit-i18n/lib/issues/149#issuecomment-5663561512) — and the defect that reached users, the documented recipe rendering a blank page on an unmatched route, is already fixed in `docs/`.

## Absorbs

- #149 — error pages show raw keys on first access (error pages don't run `load`, so nothing loads their translations)
- #167 — static adapter with the advanced router (default locale without prefix): no working recipe
- #185 — `locale-router` example fails under `prerender = true` (crawler cannot discover `/[lang]/…` routes)

### Recipes

Rebuild the routing examples on the v3 idiom (`export const i18n = new I18n(config)`), covering:

- `locale-router` with **prerendering**: explicit `entries` generation for all locales, verified crawl;
- **static adapter** variant, including default-locale-without-prefix — this is the configuration the site runs on, so the example is its distillation;
- **error-page translation recipe** — the documented pattern for `+error.svelte`, which never runs `load`. This has to settle the **fully-prerendered vs SPA-fallback** question explicitly, not only the happy path: a statically hosted site serves unknown paths from a `404.html` shell, which is precisely the state #149 describes, so the recipe has to say what the error page may rely on in each case;
- **MDsveX (`.svx`) route** - a page showing that `.svx` compiles to an ordinary Svelte component, so `t` works in it unchanged, and the part that actually bites: how such a route participates in route-scoped loaders and in the prerender entries above. Asked in discussion #67.

### Matrix

The matrix shrinks from 14 applications to 8. An example earns its place only when the thing it demonstrates is **application-shaped** — an adapter, a `svelte.config.js`, `hooks.server.js`, a route tree. Everything that is really three lines of configuration is documentation, and becomes a playground panel on the site (#253).

Stays, rebuilt on v3 and smoke-built in CI:

- `multi-page`
- `locale-param`
- `locale-router` (non-static adapter, prerendering)
- `locale-router-static`
- `locale-router-advanced` (default locale without prefix)
- `component-scoped-csr`
- `component-scoped-ssr`
- `mdsvex` (new)

Moves to #253: `parser-default` (now `parser-curly`), `parser-icu`, `preprocess`, `loaders`, `fallback-locale`, `single-load`, `one-page`.

### Hosting and CI

- **Drop the per-example deployments.** All 14 carry a `netlify.toml` and a separate Netlify site; that is 14 deployments to keep alive for 14 demos nobody re-deployed after a dependency bump. Remove the files and the demo links; `examples/README.md` links to the source and to a StackBlitz/SvelteLab launcher generated from the repository, which cannot go stale. The site (#253) becomes the one deployed demo.
- **Smoke-build every example in CI — asserting on output, not on the exit code.** `pnpm install` at the root already pays for the examples' dependencies but never builds them, which is how they rotted unnoticed. But a build that exits 0 proves nothing here: once `handleError` returns a well-formed error, a prerender writes an error page for every route and still succeeds. The step has to assert that a known translated string appears in the prerendered HTML.
- **Rewrite before wiring CI.** The examples resolve `sveltekit-i18n` through the workspace, so they already build against 3.0.0 and already fail — they call `locales.get()`, `loading.subscribe()`, `translations.get()` and destructure `t`, none of which exist in v3.
- **`handleError` must return a well-formed `App.Error`.** Every v2 example ends it with `return locals;`; with no `message`, SvelteKit's own fatal-error path throws in `escape_html(undefined)` and masks the real error.
- **Bump the examples' dependencies.** They sit on `@sveltejs/kit ^2.61`, `vite ^7.3` and `@sveltejs/vite-plugin-svelte ^6`, while the library itself is on vite 8 and plugin-svelte 7.

## Notes

The three absorbed issues stay open until their scenario has a working, CI-built example.

Out of scope for the MDsveX case: translating the markdown *content* itself. One `.svx` file per locale is a routing and content decision, not something this library resolves - the example covers the component-level usage and the loading, not authoring localized prose.

The existing Netlify sites have to be deleted in the Netlify account; removing `netlify.toml` here only stops future builds.

**Comment by jarda-svoboda** [comment]
Groundwork done. Four findings that change how this issue has to be executed.

## 1. The prerender / fallback question is settled

Measured on a minimal v3 app built with `adapter-static`:

- **`fallback: '404.html'`** produces an empty SPA shell — 1 147 bytes, no server-rendered markup at all. The error page is rendered on the client after hydration. Fine for a 404; it means no markup for crawlers and nothing without JavaScript.
- **Strict full prerender** never runs the app for an unknown URL; the host serves its own 404 and the application is not involved.

Both belong in the examples, spelled out, because the choice decides what `+error.svelte` may rely on. The diagnosis of the error-page failure itself is in #149.

## 2. `pnpm build` exiting 0 does not mean the example works

The planned CI smoke build is not sufficient as specified. Building `locale-router-static` against v3 fails with `TypeError: locales.get is not a function` — but once `handleError` returns a well-formed error, the prerender "succeeds", writes an error page for every route, and **the build exits 0**. A green build would have told us nothing.

The CI step therefore has to assert on the generated output — that a known translated string appears in the prerendered HTML — not merely on the exit code.

## 3. `handleError` returning `locals` breaks SvelteKit's own fallback error page

Every v2 example ends `handleError` with `return locals;`. With no `message` property, SvelteKit's fatal-error path calls `escape_html(undefined)` and throws, which **masks the real error** — the underlying failure only became visible after the hook was instrumented. The rebuilt examples must return a proper `App.Error` shape.

## 4. Ordering inside this issue

The CI smoke build cannot be the first step, as the current scope implies. The examples resolve `sveltekit-i18n` through the workspace, so they already build against 3.0.0 and already fail: they call `locales.get()`, `loading.subscribe()`, `translations.get()` and destructure `t`, none of which exist in v3. Rewrite first, then wire CI.

---

Side note, not in scope here: a consumer whose app does not declare `sveltekit-i18n` as a dependency (so `vite-plugin-svelte` cannot add the core to `ssr.noExternal`) gets `$state is not defined` from `base/dist/I18n.svelte.js`, with nothing pointing at the cause. `docs/` covers externalization only for Vitest. Worth a `TROUBLESHOOTING.md` entry — there is already a `$state is not defined` section that could carry it.


---
_Generated by [Claude Code](https://claude.ai/code)_
